### ISSUE TITLE
blinds control

### ISSUE THREAD

**Issue by roninriddle** [lawtancool/pyControl4#13]
Hi Lawtancool
I found you have already update blind control to this components,
would you like upadte it to the official Home Assistant Control4 integration?
It is more friendly to use for people like me.

Thanks a lot.

**Comment by lawtancool** [comment]
I do not own any Control4 blinds, so I won't be able to write a Home Assistant integration for it. If someone who owns Control4 blinds is willing to develop/test an integration and open a PR with the Home Assistant core, I would be happy to review it.

**Comment by roninriddle** [comment]
I can help with testing this intergration, BTW i use the inSona DT82TE Motor to control my blinds.

**Comment by lawtancool** [comment]
Closed by #11
