### ISSUE TITLE
Error in usage example, SSL Error

### ISSUE THREAD

**Issue by ctmanley** [lawtancool/pyControl4#2]
I ran test.py to test and get started. I replace username and password with my login username and password.  I replaced ip with the ip of my EA-5 controller.  The controller is running OS 3.1.1

When I run the test, I get the following error:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host apis.control4.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)')]

for this statement

asyncio.run(account.getAccountBearerToken())

Which is just after the statement: account = C4Account(username, password)

Is there something that needs to be configured in addition to username, password and ip?  Is there a C4 drive needed to use this code?

**Comment by lawtancool** [comment]
I've never seen this error before - it appears to be something wrong with your local Python installation or internet access.
