### ISSUE TITLE
Integration cannot work without internet?

### ISSUE THREAD

**Issue by nalin29** [lawtancool/pyControl4#28]
I am currently owning parts of HA C4 integration. And I was doing some updating and noticed that if the internet goes out or C4 decides to pull the plug on those APIs we use for account tokens and directors this will no longer work? Is that how C4 already does things through their app, or is there some other way.

Thanks for the work just concerned about this possibility.

**Comment by lawtancool** [comment]
Yes, this is the way C4 does things through the app. I don't know of any way to connect to the C4 Director without authenticating with Control4's cloud servers.
