### ISSUE TITLE
Remove socket.io constraint 

### ISSUE THREAD

**Issue by balloob** [lawtancool/pyControl4#31]
This package is currently preventing any integration in Home Assistant from using a modern version of socketio. Could you loosen the constraint ? 

https://github.com/home-assistant/core/actions/runs/10587057568/job/29337060016?pr=124672

**Comment by lawtancool** [comment]
We do need this old version to work with Control4 systems. Please see my reply here: https://github.com/home-assistant/core/pull/124746#issuecomment-2313758191

**Comment by bdraco** [comment]
https://pypi.org/project/python-socketio-v4/ has been published and can be used as an alternative. Everything is the same except the namespace is now `socketio_v4` instead of `socketio`
