### ISSUE TITLE
Is repo active?

### ISSUE THREAD

**Issue by Xorso** [lawtancool/pyControl4#7]
@lawtancool Many thanks for this integration. I have always loved Home-Assistant and to marry it with my Control4 is great.

I wanted to know you are actively checking your repo as I have invested some time on looking into using websockets (instead of polling) to update and discover devices (as well as supporting motion detectors as well). 

I wanted to get feedback before I put together a PR.

Thanks

**Comment by lawtancool** [comment]
Hi @Xorso,

A websockets PR would be very much appreciated, as I haven't been able to figure that out myself. To answer your question, I do check this repo :)

**Comment by Xorso** [comment]
Perfect! I will clean up my changes and see if I can get it submitted within the next week or two.
